> ### Iris dataset

Each data point represents an iris flower, and the dataset includes four features (attributes) for each flower. These features are measurements of the flowers' physical characteristics. Specifically, the features are:

      1. Sepal Length: The length of the sepal (in cms)

      2. Sepal Width: The width of the sepal (in cms)

      3. Petal Length: The length of the petal (in cms)

      4. Petal Width: The width of the petal (in cms)

### Explanation of Sepal and Petal:
   - **Sepal**: The sepal is the part of the flower that typically forms the outermost whorl of the flower. Sepals are usually green and function as protection for the flower in bud and often as support for the petals when in bloom.

   - **Petal**: The petal is the part of the flower that is often colorful and attracts pollinators. Petals are usually located inside the sepals.


### Visual Representation:
Here is a simple diagram to illustrate the sepal and petal:

```
      _______
     /       \
    /         \
   /  Sepal    \
  /_____________\
  \             /
   \   Petal   /
    \_________/
```

### Example Data Point:
A single data point in the Iris dataset might look like this:
   ```
   [5.1, 3.5, 1.4, 0.2]
   ```
      This corresponds to:

      - Sepal Length: 5.1 cm

      - Sepal Width: 3.5 cm

      - Petal Length: 1.4 cm
      
      - Petal Width: 0.2 cm

### Loading and Viewing the Iris Dataset is shown below:

In [1]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
import pandas as pd

# Load the iris dataset
iris = load_iris()
X, y  = iris.data, iris.target

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, 
                                                    test_size = 0.3, 
                                                    random_state = 42)

# Print the shapes of X_train and y_train
print('Shape of X:', X.shape)                           # Shape of X: i.e, iris dataset is (150, 4) --> 150 rows and 4 columns
print('Shape of y:', y.shape)
print('Shape of X_train:', X_train.shape)               # X_train and all related X entities [iris.data] are 2D array
print('Shape of y_train:', y_train.shape)               # y_train and all related y entities [iris.target] are are 1D array
print('Shape of X_test:', X_test.shape)
print('Shape of y_test:', y_test.shape)

# Print the first few rows of X_train and y_train
print('\nFirst 5 rows of X_train:')
print(X_train[:5])
print(X_train.dtype)
print('\nFirst 5 rows of y_train:')
print(y_train[:5])


# Create a DataFrame for better visualization
iris_df = pd.DataFrame(data = iris.data, columns = iris.feature_names)
iris_df['target'] = iris.target

# Display the first few rows of the DataFrame
print(iris_df.head())                                   # In this dataset, the `target` column represents the species of the iris flower, encoded as integers (0, 1, 2).



Shape of X: (150, 4)
Shape of y: (150,)
Shape of X_train: (105, 4)
Shape of y_train: (105,)
Shape of X_test: (45, 4)
Shape of y_test: (45,)

First 5 rows of X_train:
[[5.5 2.4 3.7 1. ]
 [6.3 2.8 5.1 1.5]
 [6.4 3.1 5.5 1.8]
 [6.6 3.  4.4 1.4]
 [7.2 3.6 6.1 2.5]]
float64

First 5 rows of y_train:
[1 2 2 1 2]
   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0  


In [2]:
print(type(iris.data))
print(iris.data.size)

<class 'numpy.ndarray'>
600


In [4]:
iris_df['target'] = iris.target
print(type(iris.target))
print(iris.target.size)
print(iris.target)

<class 'numpy.ndarray'>
150
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
